# partition.conf
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: "300M"
efiSystemPartitionName: "EFI"
userSwapChoices:
  - none
  - reuse
  - file
defaultFileSystemType: "ext4"
availableFileSystemTypes: ["ext4", "btrfs", "xfs"]
allowManualPartitioning: true
initialPartitioningChoice: erase
initialSwapChoice: file
